console_access_settings:
console_endpoint: "https://console.aitrios.sony-semicon.com/api/v1"
portal_authorization_endpoint : "https://auth.aitrios.sony-semicon.com/oauth2/default/v1/token"
client_secret: "{IZX5FSn0U_ErVQ30YmOP8_NLFBMydn1Ax8sfliW0UnAFPx8nUiC5GMtSN5yIxVu}"
client_id: "{0oa3r62ofa2m5HPSh697}"
